"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Student_1 = require("./Student");
var StudentManager_1 = require("./StudentManager");
var student1 = new Student_1.Student("An", "C0322H1", 9);
var student2 = new Student_1.Student("An 2", "C0322H1", 10);
var student3 = new Student_1.Student("An 3", "C0322H1", 9);
var student4 = new Student_1.Student("Thịnh Cá chép 2", "C0322H1", 2);
var student5 = new Student_1.Student("Thịnh Cá chép 3", "C0322H1", 5);
var student6 = new Student_1.Student("Thịnh Cá chép 4", "C0322H1", 4);
var student7 = new Student_1.Student("Thành 5K 2", "C0322H1", 7);
var student8 = new Student_1.Student("Thành 5K 3", "C0322H1", 6);
var student9 = new Student_1.Student("Thành 5K 5", "C0322H1", 8);
var student10 = new Student_1.Student("Thành 5K 6", "C0322H1", 8);
var listStudents = new StudentManager_1.StudentManager();
listStudents.add(student1, student2, student3, student4, student5, student6, student7, student8, student9);
listStudents.add(student10);
console.log(listStudents.statistical());
var students = listStudents.students;
console.log(students);
